# Generated by Django 4.2.23 on 2025-08-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
